# Generated by Django 4.1.2 on 2023-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_customuser_delete_user_alter_comment_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='users',
            field=models.ManyToManyField(to='posts.customuser'),
        ),
    ]
